In [3]:
import numpy
import numpy as np

In [17]:
nparr = numpy.array([1,2,3,4]) #1 dimensional array
print(nparr)
nparr.shape

[1 2 3 4]


(4,)

In [18]:
nparr = numpy.array([[1,2,3,4],[1,2,3,4]]) #2 dimensional array
print(nparr)
nparr.shape

[[1 2 3 4]
 [1 2 3 4]]


(2, 4)

In [6]:
(np.random.random((3,4)))
                 

array([[0.98894548, 0.97548528, 0.48733406, 0.46962832],
       [0.58600668, 0.6585126 , 0.46192216, 0.08318549],
       [0.02678478, 0.85250981, 0.58593808, 0.15565272]])

In [19]:
nparr = numpy.array([x for x in range( 30)])
print(nparr)
print(nparr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
(30,)


In [20]:
reshaped = nparr.reshape(2,5,3)
print(reshaped)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [28]:
numpy_gen = numpy.arange(30) #generate in steps of 1
print(numpy_gen)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [22]:
numpy_gen = numpy.arange(3,6,1) #arange
print(numpy_gen)

[3 4 5]


In [23]:
numpy_gen = numpy.linspace(3,6,6) #linspace
print(numpy_gen)

[3.  3.6 4.2 4.8 5.4 6. ]


In [24]:
for row in numpy_gen:
    print(row)

3.0
3.6
4.2
4.8
5.4
6.0


In [25]:
for table in reshaped:#iterate over np array
#     print(table)
    for row in table:
        print(row)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]
[24 25 26]
[27 28 29]


In [38]:
numpy_gen[1]
new_arr = numpy_gen.reshape(5,6)
print(new_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [37]:
new_arr[:,0]

array([ 0,  6, 12, 18, 24])

In [39]:
x = numpy.linspace(1,20,20)
y = numpy.linspace(1,50,20)
print(x,y)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.] [ 1.          3.57894737  6.15789474  8.73684211 11.31578947 13.89473684
 16.47368421 19.05263158 21.63157895 24.21052632 26.78947368 29.36842105
 31.94736842 34.52631579 37.10526316 39.68421053 42.26315789 44.84210526
 47.42105263 50.        ]


In [41]:
stacked = numpy.column_stack((x,y))

In [45]:
# print(stacked)
for item in stacked.flat :
    print (item)

1.0
1.0
2.0
3.5789473684210527
3.0
6.157894736842105
4.0
8.736842105263158
5.0
11.31578947368421
6.0
13.894736842105264
7.0
16.473684210526315
8.0
19.05263157894737
9.0
21.63157894736842
10.0
24.210526315789473
11.0
26.789473684210527
12.0
29.36842105263158
13.0
31.94736842105263
14.0
34.526315789473685
15.0
37.10526315789474
16.0
39.68421052631579
17.0
42.26315789473684
18.0
44.8421052631579
19.0
47.421052631578945
20.0
50.0


In [ ]:
import pandas 
_ddict = {'name':[1,2,3,4]}
